version: "3.8"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "gunicorn"
      - "auth_service.wsgi:application"
      - "--bind"
      - "0.0.0.0:8080"
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./auth_service/database:/app/database